//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_EMPRESA> TB_EMPRESA { get; set; }
        public virtual DbSet<TB_SETOR> TB_SETOR { get; set; }
        public virtual DbSet<TB_TIPO_EMPREGO> TB_TIPO_EMPREGO { get; set; }
        public virtual DbSet<TB_VAGA> TB_VAGA { get; set; }
    }
}
