//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VAGA
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public decimal salario { get; set; }
        public int id_empresa { get; set; }
        public int id_tipo_emprego { get; set; }
    
        public virtual TB_EMPRESA TB_EMPRESA { get; set; }
        public virtual TB_TIPO_EMPREGO TB_TIPO_EMPREGO { get; set; }
    }
}
