CREATE TABLE TB_SETOR(
	id INT IDENTITY(1, 1) NOT NULL,
	descricao VARCHAR(100) NOT NULL,
	CONSTRAINT pk_setor PRIMARY KEY(id)
);

CREATE TABLE TB_TIPO_EMPREGO(
	id INT IDENTITY(1, 1) NOT NULL,
	descricao VARCHAR(100) NOT NULL,
	CONSTRAINT pk_tipo_emprego PRIMARY KEY(id)
);

CREATE TABLE TB_EMPRESA(
	id INT IDENTITY(1, 1) NOT NULL,
	nome VARCHAR(100) NOT NULL,
	telefone VARCHAR(15) NOT NULL,
	id_setor INT NOT NULL,
	CONSTRAINT pk_empresa PRIMARY KEY(id),
	CONSTRAINT fk_empresa_setor FOREIGN KEY(id_setor) REFERENCES TB_SETOR(id)
);

CREATE TABLE TB_VAGA(
	id INT IDENTITY(1, 1) NOT NULL,
	titulo VARCHAR(100) NOT NULL,
	descricao VARCHAR(5000) NOT NULL,
	salario DECIMAL(8, 2) NOT NULL,
	id_empresa INT NOT NULL,
	id_tipo_emprego INT NOT NULL,
	CONSTRAINT pk_vaga PRIMARY KEY(id),
	CONSTRAINT fk_vaga_empresa FOREIGN KEY(id_empresa) REFERENCES TB_EMPRESA(id),
	CONSTRAINT fk_vaga_tipo_emprego FOREIGN KEY(id_tipo_emprego) REFERENCES TB_TIPO_EMPREGO(id)
);